In [1]:
import numpy as np  
# 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np   
#복수 객체 저장 및 불러오기
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('savez.npz', arrays1=array1, arrays2=array2)

data = np.load('savez.npz')
result1 = data['arrays1']
result2 = data['arrays2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [20]:
import numpy as np  
# Numpy 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)
# 내림차순
print(array[::-1])
# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [56]:
import numpy as np
# 균일한 간격으로 데이터 생성
array = np.linspace(0, 50, 11)
print(array)
# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))
# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2)
array2[0] = 100
print(array1)
print(array2)
#중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[1 2 3]
