# Heading1
## Heading2   

In [1]:
import numpy as np
data = np.array([2,4,7,9.1])
data.ndim


1

In [2]:
data.shape

(4,)

In [3]:
data.dtype

dtype('float64')

In [4]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr_sub = arr[0, 0:2]
arr_sub

array([1, 2])

In [6]:
arr[0, 0:2] = [99, 88]
arr

array([[99, 88,  3],
       [ 4,  5,  6]])

In [7]:
arr_sub

array([99, 88])

In [8]:
nums = [1,2,2,5,8,8]
len(nums)
set(nums)
list(set(nums))
np.unique(nums)
len(np.unique(nums))

4

In [20]:
import pandas as pd
pd.DataFrame()
ser = pd.Series([2,4,6,8])
ser

data = {
    '이름' : ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교' : ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
df = pd.DataFrame(data)
#df[['키', '이름']]
df.head()

df['키'].nlargest(3)
df['키'].describe()

count      8.000000
mean     188.000000
std        9.985704
min      168.000000
25%      186.250000
50%      188.000000
75%      191.750000
max      202.000000
Name: 키, dtype: float64

In [22]:
import pandas as pd 
import numpy as np
df = pd.read_json("./DataSet/bike.json")
df.describe()
df_sub = df[df.season == 3]
df_sub.head()
df_sub.shape
df_sub2 = df[(df.season == 1) & (df.holiday == 1)]
df_sub2.head()
df_sub = df.iloc[np.in1d(df.season, [1, 2]), :]
set(df_sub.season)

{1, 2}

In [32]:
mat = np.matrix([[1, 2],
                 [3, 4]])

mat * mat

matrix([[ 7, 10],
        [15, 22]])

In [34]:
ndr = np.array([[1, 2],
                [3, 4]])

ndr + 3

ndr * ndr

array([[ 1,  4],
       [ 9, 16]])